# Generated by Django 4.1.7 on 2023-07-02 17:35

import CAadmin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=CAadmin.models.get_current_date)),
            ],
        ),
        migrations.CreateModel(
            name='CA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('profile_photo', models.FileField(default=CAadmin.models.get_default_profile_photo, upload_to='profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], max_length=10)),
                ('company_type', models.CharField(blank=True, max_length=50, null=True)),
                ('residence_status', models.CharField(choices=[('Resident', 'Resident'), ('Non-Resident', 'Non-Resident')], max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('category', models.CharField(choices=[('Category A', 'Category A'), ('Category B', 'Category B'), ('Category C', 'Category C')], max_length=50)),
                ('group_with', models.CharField(choices=[('Group 1', 'Group 1'), ('Group 2', 'Group 2'), ('Group 3', 'Group 3')], max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('profile_photo', models.FileField(default=CAadmin.models.get_default_profile_photo, upload_to='profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('messaeg', models.CharField(max_length=255)),
                ('ref', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('profile_photo', models.FileField(default=CAadmin.models.get_default_profile_photo, upload_to='profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Client'), ('Client', 'Client')], max_length=10)),
                ('profile_photo', models.FileField(default=CAadmin.models.get_default_profile_photo, upload_to='profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField(default=CAadmin.models.get_next_date)),
                ('status', models.CharField(choices=[('Todo', 'Todo'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Verified', 'Verified')], max_length=20)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('start_date', models.DateTimeField(default=CAadmin.models.get_current_date)),
                ('end_date', models.DateTimeField(default=CAadmin.models.get_next_date)),
                ('assign_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CAadmin.employee')),
                ('tags', models.ManyToManyField(to='CAadmin.tag')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAadmin.client')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='media/personal_files')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CAadmin.client')),
            ],
        ),
        migrations.CreateModel(
            name='General_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='media/general_files')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CAadmin.client')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAadmin.client')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Office', 'Office'), ('Residence', 'Residence')], max_length=50)),
                ('building_number', models.CharField(max_length=50)),
                ('floor_number', models.CharField(max_length=50)),
                ('name_of_building', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('City 1', 'City 1'), ('City 2', 'City 2'), ('City 3', 'City 3')], max_length=50)),
                ('state', models.CharField(choices=[('State 1', 'State 1'), ('State 2', 'State 2'), ('State 3', 'State 3')], max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAadmin.client')),
            ],
        ),
    ]
