# Generated by Django 4.1.7 on 2023-05-27 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], max_length=10)),
                ('company_type', models.CharField(blank=True, max_length=50, null=True)),
                ('residence_status', models.CharField(choices=[('Resident', 'Resident'), ('Non-Resident', 'Non-Resident')], max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('category', models.CharField(choices=[('Category A', 'Category A'), ('Category B', 'Category B'), ('Category C', 'Category C')], max_length=50)),
                ('group_with', models.CharField(choices=[('Group 1', 'Group 1'), ('Group 2', 'Group 2'), ('Group 3', 'Group 3')], max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('file', models.FileField(upload_to='personal_files/')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CAadmin.client')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAadmin.client')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Office', 'Office'), ('Residence', 'Residence')], max_length=50)),
                ('building_number', models.CharField(max_length=50)),
                ('floor_number', models.CharField(max_length=50)),
                ('name_of_building', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('City 1', 'City 1'), ('City 2', 'City 2'), ('City 3', 'City 3')], max_length=50)),
                ('state', models.CharField(choices=[('State 1', 'State 1'), ('State 2', 'State 2'), ('State 3', 'State 3')], max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CAadmin.client')),
            ],
        ),
    ]
