# Generated by Django 4.1.7 on 2023-05-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAadmin', '0003_ca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
