# Generated by Django 4.1.7 on 2023-06-22 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAadmin', '0010_personal_file_general_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Todo', 'Todo'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Verified', 'Verified')], max_length=20)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assign_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CAadmin.employee')),
                ('tags', models.ManyToManyField(to='CAadmin.tag')),
            ],
        ),
    ]
