# Generated by Django 4.1.7 on 2023-06-26 15:38

import CAadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAadmin', '0013_alter_task_assign_to_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ca',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='client',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(default=CAadmin.models.get_next_date),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=CAadmin.models.get_current_date),
        ),
    ]
