# Generated by Django 4.1.7 on 2023-06-26 15:44

import CAadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAadmin', '0014_ca_profile_photo_client_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='profile_photo',
            field=models.FileField(default=CAadmin.models.get_default_profile_photo, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_photo',
            field=models.FileField(default=CAadmin.models.get_default_profile_photo, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_photo',
            field=models.FileField(default=CAadmin.models.get_default_profile_photo, upload_to='profiles'),
        ),
    ]
