# Generated by Django 4.1.7 on 2023-06-26 16:35

import CAadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAadmin', '0015_alter_ca_profile_photo_alter_client_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='profile_photo',
            field=models.FileField(default=CAadmin.models.get_default_profile_photo, upload_to='profiles'),
        ),
    ]
