# Generated by Django 4.1.7 on 2023-06-27 09:03

import CAadmin.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAadmin', '0016_login_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='profile_photo',
            field=models.ImageField(default=CAadmin.models.get_default_profile_photo, upload_to='profiles'),
        ),
    ]
