# Generated by Django 4.1.7 on 2023-06-28 04:36

import CAadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAadmin', '0017_alter_ca_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='profile_photo',
            field=models.FileField(default=CAadmin.models.get_default_profile_photo, upload_to='profiles'),
        ),
    ]
